# Generated by Django 2.0.2 on 2018-11-02 08:02

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=30)),
                ('introduction', models.CharField(max_length=180)),
                ('images', models.CharField(max_length=180)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
