# Generated by Django 2.0.2 on 2018-11-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.CharField(max_length=360),
        ),
    ]
